/**
 * Country name to ISO 3166-1 alpha-2 code mapping.
 * Used to convert nationality from football-data.org to country codes.
 */

export const COUNTRY_CODES: Record<string, string> = {
  // Europe
  'England': 'GB',
  'Scotland': 'GB',
  'Wales': 'GB',
  'Northern Ireland': 'GB',
  'Republic of Ireland': 'IE',
  'Ireland': 'IE',
  'France': 'FR',
  'Germany': 'DE',
  'Spain': 'ES',
  'Italy': 'IT',
  'Portugal': 'PT',
  'Netherlands': 'NL',
  'Belgium': 'BE',
  'Croatia': 'HR',
  'Serbia': 'RS',
  'Switzerland': 'CH',
  'Austria': 'AT',
  'Poland': 'PL',
  'Ukraine': 'UA',
  'Czech Republic': 'CZ',
  'Czechia': 'CZ',
  'Denmark': 'DK',
  'Sweden': 'SE',
  'Norway': 'NO',
  'Finland': 'FI',
  'Greece': 'GR',
  'Turkey': 'TR',
  'Russia': 'RU',
  'Romania': 'RO',
  'Hungary': 'HU',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Bosnia and Herzegovina': 'BA',
  'Bosnia-Herzegovina': 'BA',
  'Montenegro': 'ME',
  'North Macedonia': 'MK',
  'Albania': 'AL',
  'Kosovo': 'XK',
  'Iceland': 'IS',
  'Luxembourg': 'LU',
  'Moldova': 'MD',
  'Belarus': 'BY',
  'Bulgaria': 'BG',
  'Georgia': 'GE',
  'Armenia': 'AM',
  'Azerbaijan': 'AZ',
  'Cyprus': 'CY',
  'Malta': 'MT',
  'Estonia': 'EE',
  'Latvia': 'LV',
  'Lithuania': 'LT',

  // South America
  'Brazil': 'BR',
  'Argentina': 'AR',
  'Uruguay': 'UY',
  'Colombia': 'CO',
  'Chile': 'CL',
  'Peru': 'PE',
  'Ecuador': 'EC',
  'Paraguay': 'PY',
  'Venezuela': 'VE',
  'Bolivia': 'BO',

  // North/Central America & Caribbean
  'Mexico': 'MX',
  'United States': 'US',
  'USA': 'US',
  'Canada': 'CA',
  'Jamaica': 'JM',
  'Costa Rica': 'CR',
  'Honduras': 'HN',
  'Panama': 'PA',
  'Guatemala': 'GT',
  'El Salvador': 'SV',
  'Haiti': 'HT',
  'Trinidad and Tobago': 'TT',
  'Curaçao': 'CW',
  'Suriname': 'SR',

  // Africa
  'Nigeria': 'NG',
  'Egypt': 'EG',
  'Morocco': 'MA',
  'Senegal': 'SN',
  'Ghana': 'GH',
  'Cameroon': 'CM',
  'Ivory Coast': 'CI',
  "Côte d'Ivoire": 'CI',
  'Algeria': 'DZ',
  'Tunisia': 'TN',
  'Mali': 'ML',
  'DR Congo': 'CD',
  'Congo DR': 'CD',
  'South Africa': 'ZA',
  'Gabon': 'GA',
  'Guinea': 'GN',
  'Burkina Faso': 'BF',
  'Zimbabwe': 'ZW',
  'Zambia': 'ZM',
  'Kenya': 'KE',
  'Uganda': 'UG',
  'Tanzania': 'TZ',
  'Angola': 'AO',
  'Mozambique': 'MZ',
  'Cape Verde': 'CV',
  'Cabo Verde': 'CV',
  'Equatorial Guinea': 'GQ',
  'Togo': 'TG',
  'Benin': 'BJ',
  'Niger': 'NE',
  'Mauritania': 'MR',
  'Gambia': 'GM',
  'Sierra Leone': 'SL',
  'Liberia': 'LR',
  'Central African Republic': 'CF',
  'Congo': 'CG',
  'Madagascar': 'MG',
  'Comoros': 'KM',
  'Guinea-Bissau': 'GW',

  // Asia
  'Japan': 'JP',
  'South Korea': 'KR',
  'Korea Republic': 'KR',
  'Korea, South': 'KR',
  'Korea, Republic of': 'KR',
  'China': 'CN',
  'China PR': 'CN',
  'Iran': 'IR',
  'Saudi Arabia': 'SA',
  'Australia': 'AU',
  'Israel': 'IL',
  'Uzbekistan': 'UZ',
  'Qatar': 'QA',
  'United Arab Emirates': 'AE',
  'Iraq': 'IQ',
  'Syria': 'SY',
  'Jordan': 'JO',
  'Lebanon': 'LB',
  'Palestine': 'PS',
  'Vietnam': 'VN',
  'Thailand': 'TH',
  'Indonesia': 'ID',
  'Malaysia': 'MY',
  'Philippines': 'PH',
  'India': 'IN',
  'Pakistan': 'PK',
  'Bangladesh': 'BD',
  'Nepal': 'NP',
  'Kazakhstan': 'KZ',
  'Tajikistan': 'TJ',
  'Kyrgyzstan': 'KG',
  'Turkmenistan': 'TM',
  'Afghanistan': 'AF',
  'Bahrain': 'BH',
  'Kuwait': 'KW',
  'Oman': 'OM',
  'Yemen': 'YE',

  // Oceania
  'New Zealand': 'NZ',
  'Fiji': 'FJ',
  'Papua New Guinea': 'PG',
};

/**
 * Get country code from nationality name.
 * Returns 'XX' if not found.
 */
export function getCountryCode(nationality: string): string {
  return COUNTRY_CODES[nationality] ?? 'XX';
}
